language: c
sudo: required
addons:
  apt:
    packages:
      - build-essential
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty-updates main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -y linux-headers-`uname -r`
script:
  - make
notifications:
  on_success: never
  on_failure: never
